
[package]
name = "solana-application-fees-program-tests"
version = "1.15.0"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2021"
publish = false

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
solana-application-fees-program = { path = "../application-fees", version = "=1.15.0" }
solana-program-test = { path = "../../program-test", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
